# Generated by Django 5.1.2 on 2024-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='biografia',
            field=models.TextField(default=' ', max_length=200),
        ),
    ]
