# Generated by Django 5.1.2 on 2024-11-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_datosextra_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='descripcion',
            field=models.TextField(default='', max_length=100),
        ),
    ]
