# Generated by Django 5.1.2 on 2024-11-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_datosextra_descripcion_alter_datosextra_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosextra',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatares'),
        ),
    ]
