# Generated by Django 5.1.2 on 2024-11-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_datosextra_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
