# Generated by Django 5.1.2 on 2024-11-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_datosextra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosextra',
            name='fecha',
        ),
    ]
