# Generated by Django 5.1.2 on 2024-11-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_datosextra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
