# Generated by Django 5.1.2 on 2024-11-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(blank=True, upload_to='portadas')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=20)),
                ('sinopsis', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(max_length=50)),
                ('perfil', models.ImageField(blank=True, upload_to='personajes')),
                ('nombre', models.CharField(max_length=50)),
                ('alias', models.TextField(max_length=600)),
                ('genero', models.CharField(max_length=20)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('parientes', models.TextField(max_length=600)),
                ('romances', models.TextField(max_length=600)),
                ('descripcion', models.TextField(max_length=600)),
            ],
        ),
    ]
