# Generated by Django 5.1.2 on 2024-11-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='nacimiento',
        ),
    ]
